"""add eic code registry

Revision ID: 8a8f3a664e30
Revises: bc3e4479ef9c
Create Date: 2026-09-26 13:21:37.995600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8a8f3a664e30'
down_revision: Union[str, Sequence[str], None] = 'bc3e4479ef9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eic_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eic_code', sa.String(), nullable=False),
    sa.Column('long_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('eic_parent', sa.String(), nullable=True),
    sa.Column('eic_responsible', sa.String(), nullable=True),
    sa.Column('functions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('fetched_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eic_code', name='uq_eic_code')
    )
    op.create_index(op.f('ix_eic_code_eic_code'), 'eic_code', ['eic_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eic_code_eic_code'), table_name='eic_code')
    op.drop_table('eic_code')
    # ### end Alembic commands ###
