"""added borders flow and DC capacity

Revision ID: bc3e4479ef9c
Revises: 3bfefce53d2c
Create Date: 2026-09-20 08:17:57.317797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc3e4479ef9c'
down_revision: Union[str, Sequence[str], None] = '3bfefce53d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cross_border_capacity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('flow_destination', sa.String(), nullable=False),
    sa.Column('flow_origin', sa.String(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone', 'timestamp', name='uq_cross_border_capacity_zone_timestamp')
    )
    op.create_table('zone_physical_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('flow_destination', sa.String(), nullable=False),
    sa.Column('flow_origin', sa.String(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone', 'timestamp', name='uq_zone_physical_flows_zone_timestamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zone_physical_flows')
    op.drop_table('cross_border_capacity')
    # ### end Alembic commands ###
