"""add fetched_at to price demand weather

Revision ID: ce04a752f54a
Revises: 8a8f3a664e30
Create Date: 2026-09-26 18:20:36.585070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce04a752f54a'
down_revision: Union[str, Sequence[str], None] = '8a8f3a664e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust for existing rows ###
    for table in ('demand', 'price', 'weather'):
        op.add_column(table, sa.Column(
            'fetched_at', postgresql.TIMESTAMP(timezone=True), nullable=False,
            server_default=sa.text('now()'),
        ))
        op.alter_column(table, 'fetched_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather', 'fetched_at')
    op.drop_column('price', 'fetched_at')
    op.drop_column('demand', 'fetched_at')
    # ### end Alembic commands ###
